# Generated by Django 2.2.11 on 2020-03-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='linktoarticle',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
