# Generated by Django 2.2.11 on 2020-04-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='placeholder',
            field=models.IntegerField(default=1),
        ),
    ]
