# Generated by Django 2.2.11 on 2020-03-21 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200320_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pubdate',
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
